services:
  tarkovpedia:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    container_name: tarkovpedia
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production
